### ISSUE TITLE
Revise the KYC process flow

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-web#1]

**Comment by Tieumsan** [comment]
@spitsynval need design and link from Artem for the flow on web. Or is it already good ?

**Comment by spitsynval** [comment]
Artem has started designing based on the SORA Wallet specification. It's currently in process. We expect to get it before 30/04.

**Comment by Tieumsan** [comment]
@RustemYuzlibaev fyi; please sync with Artem on this to ensure technical feasibility
cc. @stefashkaa

**Comment by RustemYuzlibaev** [comment]
https://www.figma.com/file/SOnJtOI73y1aqSalgrmo6D/Polkaswap-v1.x.x-(Legacy)?node-id=15133%3A317966&mode=dev

**Comment by bgodlin** [comment]
> https://www.figma.com/file/SOnJtOI73y1aqSalgrmo6D/Polkaswap-v1.x.x-(Legacy)?node-id=15133%3A317966&mode=dev

The mockups presented above need to be reviewed for any inconsistencies with the mobile version https://github.com/sora-xor/sora-card/issues/2#issuecomment-1506826434 @spitsynval

**Comment by spitsynval** [comment]
@bgodlin I have revised the web flow. It has some nice ideas that I wanted to surface, I commented in Figma.

I also have left comments highlighting the inconsistencies that need to be fixed. Mostly texts. Artem will take care of it.

**Comment by bgodlin** [comment]
> @bgodlin I have revised the web flow. It has some nice ideas that I wanted to surface, I commented in Figma.

Is my participation necessary, and is it a matter of review on my end? @spitsynval

**Comment by ra9mls** [comment]
Need to add Pending screen right after user finishes the kyc flow.

**Comment by ra9mls** [comment]
**Bug:**
1. Pass the flow with new phone number
2. Reject it on a dashboard
3. Reopen Sora Card page
4. Pass the flow again
**Actual result:**
After the passing kyc, user sees message about 0 tries left.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFdOIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--913e219533d2135588deedac6dd9daa928f54718/Screenshot%202023-09-12%20at%2011.40.19.png)
