### ISSUE TITLE
Change the point of Cam access after phone checking

### ISSUE THREAD

**Issue by ra9mls** [sora-xor/sora-card-web#13]
Now we have a worrying problem when user taps **I ALREADY APPLIED** and then taps **Lets start** he sees permission request
![Screenshot 2023-05-10 at 14.37.02.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/c48785b5-24f3-40b5-aebb-d0bed82a9568)
It can worry for some users, let's try to move this request to later step.

**Comment by RustemYuzlibaev** [comment]
done

**Comment by Tieumsan** [comment]
@RustemYuzlibaev good, then please update the status of your task to either **Review** or **Ready for Test** so that the QA team can manage it further. 

The QA team will close the task once they have tested it.

**Comment by ra9mls** [comment]
Some languages has overlapping text with icon
![Screenshot 2023-07-25 at 11.46.47.png](https://images.zenhubusercontent.com/62bbde011ca04a42bf2c5247/c4ac0d2e-68b3-4b95-8442-b2b46a9a65d7)
