### ISSUE TITLE
[Tech]: UI for SORA Card card

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora-card-web#21]
Add the SORA Card card to provide an appealing enough SORA Card hub.

Only implement the UI for the SORA Card card:

- SORA Card image
- Greyed Show details button
- Text (precise what to display instead of the amount)
- Greyed Top up/Transfer/Exchange/Freeze buttons

**Design**: https://www.figma.com/file/aDkwf6C8zmyJjudJOuuhrH/Polkaswap-(Current)?type=design&node-id=16777-9494&mode=design&t=oMtQfVwb5zRMJ7zJ-0

**Comment by Tieumsan** [comment]
@stefashkaa @RustemYuzlibaev please confirm design w/ Artem

**Comment by ra9mls** [comment]
Chat support button is absent, will be added to the next release.
