### ISSUE TITLE
Web - Calculate total balance of XOR for 2 free KYC attempts

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-card-web#23]

**Comment by ra9mls** [comment]
Have a little problem when user has pooled xor, and he opens /card page, he doesn’t see pooled xor. He needs to open pool page to get a balances and then go to /card page. It will be fixed later.

**Comment by bgodlin** [comment]
> Have a little problem when user has pooled xor, and he opens /card page, he doesn’t see pooled xor. He needs to open pool page to get a balances and then go to /card page. It will be fixed later.

@ra9mls could you please create a task for this fix
